---
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, results = TRUE)
```

# Discussion

There have been a lot of reports on estuarine salinity levels over the years on 
the channel gradient and how saltwater reacts with freshwater. However, there is 
not a lot of recent analysis of saltwater intrusion of deltas and how that could 
impact water pumping upstream for drinking water. Looking at the Delaware River for 
this project, I have noticed a pattern between streamflow and salinity that should be 
monitored for the quality of drinking water. Looking at the gradient of the Delaware 
Bay, it is surprisingly well mixed when there is usually an obvious difference between 
saltwater and freshwater [@garvine_axial_1992; @moore_oceanic_1969]. The response to river discharge from 
this well-mixed water is much weaker than we would have expected and could cause 
saltwater to flow further upstream in the future. 

At the upstream site, it has been observed in **Figure 4.** that mean discharge rates 
from 1995 to 2021 can drastically vary from year to year. For this project, I 
decided to not discuss the trends for November through May due to the application 
of road salt in the winter, since the salt is washed into the river and can falsely 
increase salinity levels. The main months I chose to discuss in more detail were the 
trends in August and September to see how discharge has changed. Which in **Figure 5.** 
there is a significant increase in mean discharge and **Figure 6.** shows an insignificant 
increase in mean discharge using the Mann-Kendall test. With discharge increasing, 
I wanted to see how salinity levels react to it and if it is a problem or not. 

So in order to get salinity data, I downloaded mean specific conductivity data 
from 1995 to 2021 at the upstream site as seen in **Figure 8.** which if you look 
at August and September there was a recent spike in salinity levels in the last 
few years. Taking a closer look in **Figure 9.**, I compared the Estuary site and the 
Middle site’s specific conductivity from March 2021 to April 2022. As expected 
the Estuary site had a larger amount of salinity and the middle site had more 
drastic changes over the year, but they do correspond with each other. Using the 
Mann-Kendall test on this figure, I found that there is also a significant 
increase in specific conductivity. 

Finally comparing discharge to specific conductivity at the Upstream site in 
**Figure 10.**, there is an interesting pattern that is formed. From 1995 to 2021, 
whenever discharge rates drop, specific conductivity levels peak in an opposite 
effect. This means that whenever a year has low streamflow, saltwater is able to 
flow further upstream, which is getting easier as sea levels rise. And as seen in 
this figure, the end of the discharge data is pointing to a dip in streamflow which 
would allow saltwater to flow upstream. To confirm this trend, I plotted specific 
conductivity with discharge by year on **Figure 11.** where you can observe a decrease 
in total discharge in comparison with salinity levels. All of the more recent points 
are on the lower end of discharge values and higher for specific conductivity. If 
these trends continue, within the next couple of years, saltwater could intrude further 
upstream than the Upstream site. This would be getting closer to the water pump, 
endangering the facility of being ruined by saltwater. 

