---
title: "Final Project"
author: "Cher Prazak"
date: "`r format(Sys.time(), '%d %h, %Y, %I:%M %p')`"
site: bookdown::bookdown_site
documentclass: docs
bibliography: WR440_biblio.bib 
output:
    bookdown::gitbook: default
    #bookdown::pdf_book: default
---

# Intro

For years, the world has been watching our climate change into what it is today.
There are people who prefer not believe in it and there are people who are very 
passionate about it. The changes that have been recorded are small, but important
for many systems on Earth. These include an increase of around one degree Celsius
and an increase in sea level by 6 to 8 inches [@epa_climate_2021]. These play a 
big part in changing pieces of our lives that we don't notice on a day to day basis.

With the sea level rising, the amount of coastal erosion has increased by a large 
amount. This has been decimating beaches and taking down coastal cliffs. There is 
already a hard time with upkeep of buildings and equipment because of the salt in 
the air which is corrosive over time. This corrosivity breaks down concrete and can 
cause a lot of problems with stability [@epa_climate_2021-1]. So, you can imagine 
how easily this can break down rocks and beaches. The rising in sea levels also 
leads to a loss of deltas, marshes, and wetlands that have important ecosystems
that they house.

Now you might be wondering how a rising sea level affects you and you would be surprised
by how much you should care. With all of these impacts, there are ones that you don't
typically see yourself. If you live by a stream that lets out into the ocean, there
are more impacts to be worried about. Such as when the tide comes in and sea water
intrudes into the freshwater areas. Now any pipes or equipment that were used to
take freshwater will have to be cleaned more often to keep from corroding 
[@epa_climate_2021-1]. And with sea levels rising, these saltwater intrusions 
will keep going further into these freshwater areas, impacting more and more parts 
of the stream.

Now if we focus on the Delaware River in New Jersey, we can look at the saltwater 
intrusion and how it has changed over the last few years. We can take this and 
compare it to sea levels in order to show how they are related and rely on each 
other[@gay_comparison_2009].In a river like the Delaware that has a well mixed 
estuary, the response to river discharge is suprisingly weak[@garvine_axial_1992].


